
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { Toaster } from 'react-hot-toast';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body  >
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.0/cdn/themes/light.css" />
        <Toaster
  position="top-center"
  reverseOrder={false}
/>
        <Navbar />
            {children}
        <Footer />
      </body>
    </html>
  );
}
